version: "3.5"
services:
  uploader:
    image: tomvanbesien/raspberry-uploader
    container_name: raspberry-uploader
    ports:
      - "8765:8080"
    volumes:
      - /c/dev/uploader/shows:/shows
      - /c/dev/uploader/movies:/movies
      - /c/dev/uploader/music:/music
    restart: "unless-stopped"
